### ISSUE TITLE
Packer Issue with ChunkedArrays

### ISSUE THREAD

**Issue by dougbrn** [lincc-frameworks/nested-dask#19]
**Bug report**
There's been a few issues with the packer that seem to be present. One reproducible example is here:

```
import nested_dask as nd

# Load some ZTF data
catalogs_dir = "https://epyc.astro.washington.edu/~lincc-frameworks/half_degree_surveys/ztf/"

object_ndf = nd.read_parquet(
    f"{catalogs_dir}/ztf_object",
    columns=["ra", "dec", "ps1_objid"],
)
source_ndf = nd.read_parquet(
    f"{catalogs_dir}/ztf_source",
    columns=["mjd", "mag", "magerr", "band", "ps1_objid", "catflags"],
)

object_ndf = object_ndf.add_nested(source_ndf, "ztf_source", how="left").compute()
```

This fails with:
```
File ~/lincc/nested-pandas/src/nested_pandas/series/packer.py:265, in view_sorted_series_as_list_array(series, offset, unique_index)
    262 if unique_index is None:
    263     unique_index = series.index[offset[:-1]]
--> 265 list_array = pa.ListArray.from_arrays(
    266     offset,
    267     pa.array(series, from_pandas=True),
    268 )
    269 return pd.Series(
    270     list_array,
    271     dtype=pd.ArrowDtype(list_array.type),
   (...)
    274     name=series.name,
    275 )

File ~/miniforge3/envs/ray310/lib/python3.10/site-packages/pyarrow/array.pxi:2203, in pyarrow.lib.ListArray.from_arrays()

TypeError: Cannot convert pyarrow.lib.ChunkedArray to pyarrow.lib.Array
```

These type errors don't seem to happen at the Nested-Pandas level (not confirmed though), so there may be something missing by just using map_partitions internally.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by hombit** [comment]
Nice catch! I believe it is `nested-pandas` issue, but I'm not sure as well...

**Comment by dougbrn** [comment]
The biggest issue with the above code is actually that the index was not set for both tables, meaning the packer was trying to pack along the default index for both tables. This is a nonsensical input so it's not clear how much to read into the packer error itself, but we should still investigate down the road:
```
import nested_dask as nd

# Load some ZTF data
catalogs_dir = "https://epyc.astro.washington.edu/~lincc-frameworks/half_degree_surveys/ztf/"

object_ndf = nd.read_parquet(
    f"{catalogs_dir}/ztf_object",
    columns=["ra", "dec", "ps1_objid"],
).set_index("ps1_objid", sort=True)

source_ndf = nd.read_parquet(
    f"{catalogs_dir}/ztf_source",
    columns=["mjd", "mag", "magerr", "band", "ps1_objid", "catflags"],
).set_index("ps1_objid", sort=True)

object_ndf = object_ndf.add_nested(source_ndf, "ztf_source", how="left")
```

**Comment by dougbrn** [comment]
This was an issue with Nested-Pandas and has been resolved.

https://github.com/lincc-frameworks/nested-pandas/issues/89
